### PR TITLE
Type sys

### PR DESCRIPTION
**Pull request by tonyfast**
* refactors the code to include most types in the `types.py` module
* uses `unittest` to help organize the tests, we still use `hypothesis`, but on `unittest`s.

### CODE REVIEW

**Comment by tonyfast** [comment]
rebased on master so we can merge

**Comment by tonyfast** [comment]
i still need to fix null testing and enum testing

**Comment by bollwyvl** [comment]
Nice, tests actually found a thing:
```
 AttributeError: module 'typing' has no attribute 'ForwardRef'
```

Looks like the backport actually exposes it as `_ForwardRef`...

**Comment by tonyfast** [comment]
i resolved the forwardref shit, but now pypy is pissed

**Comment by bollwyvl** [comment]
Looks like pypy vs hypothesis-jsonschema is no-go right now:

```
 /opt/hostedtoolcache/PyPy/3.6.12/x64/site-packages/hypothesis_jsonschema/_canonicalise.py:26: in <module>
    from ._encode import JSONType, encode_canonical_json, sort_key
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    """Canonical encoding for the JSONSchema semantics, where 1 == 1.0."""
    import json
    import math
>   from json.encoder import _make_iterencode, encode_basestring_ascii  # type: ignore
E   ImportError: cannot import name '_make_iterencode'
```

We can probably just wait it out until https://github.com/Zac-HD/hypothesis-jsonschema/issues/77 is resolved.

**Comment by bollwyvl** [comment]
fe44023 tries adding `pytest-github-actions-annotate-failures`... it's probably not going to be ready to handle as-installed packages, which are preferable from a testing perspective... may have to do some investigating, or consider working off e.g. xunit results. I guess here's hoping for flake?!

**Comment by bollwyvl** [comment]
Screenshot from 2021-03-17 01-58-34

**Comment by bollwyvl** [comment]
So that OSX fail did _not_ generate an annotation:
```
__________________________ ExoticTest.test_symbollic ___________________________

self = <schemata.tests.test_types.ExoticTest testMethod=test_symbollic>

    @hypothesis.given(examples.flatmap(type_example))
>   def test_literals(self, t):

../../../../hostedtoolcache/Python/3.9.2/x64/lib/python3.9/site-packages/schemata/tests/test_types.py:34: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../../../hostedtoolcache/Python/3.9.2/x64/lib/python3.9/site-packages/hypothesis/core.py:646: in execute_once
    self.__flaky(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
```

It would be interesting to roll back up the chain and find `schemata/tests/test_types.py:34`...

**Comment by tonyfast** [comment]
thanks for the test help @bollwyvl . errythang is green across everything and including pypy!

closing this :hankey:

**Pull request merged**
